import { Artwork } from './artwork';

export const ARTWORKS: Artwork[] = [
  { id: 3526, name: 'Painter and Dancer,', description: 'The Love portraits are sculptures of people I love with a passion that is undescribable with words. I wanted to spend time exploring thier bodies, gestures, faces and attitudes and have the sculptural process be a meditation of how these people have shaped me as a person.', year: 2009, media: 'clay with underglaze', img: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0697__large.jpg', imgZoom: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0697__zoom.jpg', imgThumb: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0697__thumb.jpg' },
  { id: 3528, name: 'Back View of Dancer and Painter', description: 'The Love portraits are sculptures of people I love with a passion that is undescribable with words. I wanted to spend time exploring thier bodies, gestures, faces and attitudes and have the sculptural process be a meditation of how these people have shaped me as a person.', year: 2009, media: 'clay with underglaze', img: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0699__large.jpg', imgZoom: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0699__zoom.jpg', imgThumb: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0699__thumb.jpg' },
  { id: 3527, name: 'Yogi and Actor', description: 'The Love portraits are sculptures of people I love with a passion that is undescribable with words. I wanted to spend time exploring thier bodies, gestures, faces and attitudes and have the sculptural process be a meditation of how these people have shaped me as a person.', year: 2009, media: 'clay with underglaze', img: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0698__large.jpg', imgZoom: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0698__zoom.jpg', imgThumb: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0698__thumb.jpg' },
  { id: 3529, name: 'Back View of Actor and Yogi,', description: 'The Love portraits are sculptures of people I love with a passion that is undescribable with words. I wanted to spend time exploring thier bodies, gestures, faces and attitudes and have the sculptural process be a meditation of how these people have shaped me as a person.', year: 2009, media: 'clay with underglaze', img: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0700__large.jpg', imgZoom: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0700__zoom.jpg', imgThumb: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0700__thumb.jpg' },
  {
    id: 3524,
    name: 'Painter, Dancer, Yogi and Actor',
    img: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0695__large.jpg',
    imgThumb: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0695__thumb.jpg',
    imgZoom: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0695__zoom.jpg',
    description: 'The Love portraits are sculptures of people I love with a passion that is undescribable with words. I wanted to spend time exploring thier bodies, gestures, faces and attitudes and have the sculptural process be a meditation of how these people have shaped me as a person.',
    year: 2009,
    media: 'clay with underglaze'
  },
  { id: 3525, name: 'Painter, Dancer, Yogi and Actor,', description: 'The Love portraits are sculptures of people I love with a passion that is undescribable with words. I wanted to spend time exploring thier bodies, gestures, faces and attitudes and have the sculptural process be a meditation of how these people have shaped me as a person.', year: 2009, media: 'clay with underglaze', img: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0696__large.jpg', imgZoom: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0696__zoom.jpg', imgThumb: 'http://www.portfolioatlas.com/gallery/artist_1214/media/-0696__thumb.jpg' }
];
